version: "3.8"

services:
  frontend:
    image: frontend-image
    container_name: frontend-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000/api
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    image: backend-image
    container_name: backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_HOST=database
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: postgres:13.2-alpine
    container_name: database-container
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
