name: Django Fullstack App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-image:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/backend-image:latest

    - name: Run Trivy Scan on Frontend Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest

    - name: Run Trivy Scan on Backend Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/backend-image:latest

    - name: Deploy with Docker Compose
      run: |
        docker-compose -f docker-compose.yml down
        docker-compose -f docker-compose.yml up -d --build